import { Providers } from "@/redux/provider";
import "./globals.css";  
import SocketHandler from "./socketHandler"; 

export const metadata = {
  title: "Peluqueria The Best",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Providers>
          {children}
          <SocketHandler />  
        </Providers>
      </body>
    </html>
  );
}
