import { Providers } from "@/redux/provider";
import "./globals.css";  // Para aplicar los estilos globales en CSS
import SocketHandler from "./socketHandler";  // Si tienes este componente para gestionar sockets

export const metadata = {
  title: "Peluqueria The Best",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Aquí puedes agregar más meta tags o enlaces a fuentes, iconos, etc. */}
      </head>
      <body>
        <Providers>
          {children}
          <SocketHandler />   {/* Mantiene la funcionalidad de sockets */}
        </Providers>
      </body>
    </html>
  );
}
